services:
  - type: web
    name: transcript-factchecker
    runtime: docker
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_FACTCHECK_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    dockerCommand: gunicorn --bind 0.0.0.0:10000 --workers 1 --timeout 120 app:app
    healthCheckPath: /health
    autoDeploy: false
