services:
  - type: web
    name: transcript-factchecker
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: false
